"""initial migration

Revision ID: 34bd8e0b7bd6
Revises: 
Create Date: 2025-04-15 05:43:29.099805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bd8e0b7bd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_giai', sa.String(length=100), nullable=False),
    sa.Column('loai_phuong_thuc', sa.String(length=50), nullable=True),
    sa.Column('gia_tri', sa.String(length=250), nullable=True),
    sa.Column('da_duoc_phat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('dia_chi', sa.String(length=200), nullable=True),
    sa.Column('ma_vung', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=20), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('thoi_gian', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_award_id'), ['award_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_award_id'))

    op.drop_table('result')
    op.drop_table('participant')
    op.drop_table('award')
    # ### end Alembic commands ###
